spring.application.name=cliente

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/db_404store_cliente
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=INFO
logging.level._store.cliente=INFO
logging.file.name=logs/cliente.log

app.jwt.secret=clave-secreta-jwt-duoc-2026-demo-123456
app.jwt.expiration-ms=3600000

